// import 'documents/msc_thesis/council_suggestion.dart' as msc_thesis;
// import 'documents/msc_thesis/score_sheet.dart' as msc_thesis;
// import 'documents/payment/listing_pdf.dart' as payment_pdfs;
// import 'documents/phd_admission/01_council_suggestion.dart' as phd_admission;
// import 'documents/phd_admission/02_score_sheet.dart' as phd_admission;
// import 'documents/phd_admission/03_payment_table.dart' as phd_admission;
export 'documents/teaching_assignment_pdf.dart';
export 'documents/payment_double_check.dart';
export 'documents/admission_payment_listing_pdf.dart';
export 'documents/admission_payment_table_pdf.dart';
export 'documents/common.dart';
export 'documents/payment/atm_pdf.dart' show PaymentAtmModel, PaymentAtmEntry;
export 'documents/payment/listing_pdf.dart';
export 'documents/payment/request_pdf.dart' show PaymentRequestModel;
export 'documents/msc_thesis_spending_decision.dart';
export 'documents/phd_admission/01_council_suggestion.dart';
export 'documents/phd_admission/02_score_sheet.dart';
export 'documents/phd_admission/03_payment_table.dart';

export 'documents/msc_thesis/assignment.dart';
export 'documents/msc_thesis/score_sheet.dart';
export 'documents/msc_thesis/council_suggestion.dart';
export 'documents/msc_thesis/council_decision.dart';
