// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    nienKhoa,
    giangvien,
    tieuBanXetTuyen,
    hocVien,
    hocky,
    hocphan,
    detaithacsi,
    phdCohort,
    phdStudent,
    dangKyGiangDay,
    lopTinChi,
    teachingAssignment,
    dangKyHoc,
    ftsDeTaiThacSi,
  ];
  late final Shape0 nienKhoa = Shape0(
    source: i0.VersionedTable(
      entityName: 'NienKhoa',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 giangvien = Shape1(
    source: i0.VersionedTable(
      entityName: 'giangvien',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 tieuBanXetTuyen = Shape2(
    source: i0.VersionedTable(
      entityName: 'TieuBanXetTuyen',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(idChuTich)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idThuKy)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idUyVien1)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idUyVien2)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idUyVien3)REFERENCES GiangVien(id)',
      ],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 hocVien = Shape3(
    source: i0.VersionedTable(
      entityName: 'HocVien',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(idTieuBanXetTuyen)REFERENCES TieuBanXetTuyen(id)',
        'FOREIGN KEY(nienKhoa)REFERENCES NienKhoa(nienKhoa)ON UPDATE CASCADE',
      ],
      columns: [
        _column_19,
        _column_26,
        _column_27,
        _column_28,
        _column_4,
        _column_13,
        _column_7,
        _column_29,
        _column_30,
        _column_11,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 hocky = Shape4(
    source: i0.VersionedTable(
      entityName: 'hocky',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 hocphan = Shape5(
    source: i0.VersionedTable(
      entityName: 'hocphan',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 detaithacsi = Shape6(
    source: i0.VersionedTable(
      entityName: 'detaithacsi',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(idChuTich)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idGiangVien)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idPhanBien1)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idPhanBien2)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idThuKy)REFERENCES GiangVien(id)',
        'FOREIGN KEY(idUyVien)REFERENCES GiangVien(id)',
      ],
      columns: [
        _column_19,
        _column_58,
        _column_53,
        _column_54,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 phdCohort = Shape7(
    source: i0.VersionedTable(
      entityName: 'phd_cohort',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_78, _column_79, _column_80],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 phdStudent = Shape8(
    source: i0.VersionedTable(
      entityName: 'phd_student',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(admission_president_id)REFERENCES giangvien(id)',
        'FOREIGN KEY(admission_president_id)REFERENCES giangvien(id)',
        'FOREIGN KEY(admission_secretary_id)REFERENCES giangvien(id)',
        'FOREIGN KEY(admission_1st_member_id)REFERENCES giangvien(id)',
        'FOREIGN KEY(admission_2nd_member_id)REFERENCES giangvien(id)',
        'FOREIGN KEY(admission_3rd_member_id)REFERENCES giangvien(id)',
        'FOREIGN KEY(supervisor_id)REFERENCES giangvien(id)',
        'FOREIGN KEY(secondary_supervisor_id)REFERENCES giangvien(id)',
      ],
      columns: [
        _column_2,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
        _column_95,
        _column_96,
        _column_97,
        _column_98,
        _column_99,
        _column_100,
        _column_101,
        _column_102,
        _column_103,
        _column_104,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 dangKyGiangDay = Shape9(
    source: i0.VersionedTable(
      entityName: 'DangKyGiangDay',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(idGiangVien, maHocPhan)',
        'FOREIGN KEY(idGiangVien)REFERENCES giangvien(id)',
        'FOREIGN KEY(maHocPhan)REFERENCES hocphan(maHocPhan)',
      ],
      columns: [_column_58, _column_105],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 lopTinChi = Shape10(
    source: i0.VersionedTable(
      entityName: 'LopTinChi',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_106,
        _column_105,
        _column_107,
        _column_108,
        _column_109,
        _column_110,
        _column_111,
        _column_112,
        _column_113,
        _column_114,
        _column_115,
        _column_116,
        _column_117,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 teachingAssignment = Shape11(
    source: i0.VersionedTable(
      entityName: 'TeachingAssignment',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(classId, teacherId)',
        'FOREIGN KEY(classId)REFERENCES LopTinChi(id)',
        'FOREIGN KEY(teacherId)REFERENCES GiangVien(id)',
      ],
      columns: [_column_118, _column_119, _column_120, _column_121],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 dangKyHoc = Shape12(
    source: i0.VersionedTable(
      entityName: 'DangKyHoc',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(idLopTinChi, idHocVien)',
        'FOREIGN KEY(idLopTinChi)REFERENCES LopTinChi(id)',
        'FOREIGN KEY(idHocVien)REFERENCES phd_student(id)',
      ],
      columns: [_column_122, _column_123],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 ftsDeTaiThacSi = Shape13(
    source: i0.VersionedVirtualTable(
      entityName: 'fts_DeTaiThacSi',
      moduleAndArgs:
          'fts5(id, idGiangVien, idHocVien, tenTiengAnh, tenTiengViet, giangVien, hocVien, tokenize="trigram remove_diacritics 1 case_sensitive 0", prefix="2 3 5 7")',
      columns: [
        _column_124,
        _column_125,
        _column_126,
        _column_127,
        _column_128,
        _column_129,
        _column_130,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get cohort =>
      columnsByName['nienKhoa']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupUrl =>
      columnsByName['groupUrl']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nienKhoa',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'groupUrl',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT ()',
      defaultValue: const CustomExpression(''),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get managementId =>
      columnsByName['maCanBo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['hoTen']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get department =>
      columnsByName['donVi']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isOutsider =>
      columnsByName['ngoaiTruong']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get gender =>
      columnsByName['gioiTinh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get academicRank =>
      columnsByName['hocHam']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get academicDegree =>
      columnsByName['hocVi']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['sdt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get personalEmail =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get citizenId =>
      columnsByName['cccd']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dateOfBirth =>
      columnsByName['ngaySinh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bankAccount =>
      columnsByName['stk']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bankName =>
      columnsByName['nganHang']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taxCode =>
      columnsByName['mst']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get academicGroupId =>
      columnsByName['ncm']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maCanBo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hoTen',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'donVi',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<bool> _column_6(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'ngoaiTruong',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT TRUE',
      defaultValue: const CustomExpression('TRUE'),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gioiTinh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hocHam',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hocVi',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sdt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'email',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cccd',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ngaySinh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stk',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nganHang',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mst',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ncm',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get year =>
      columnsByName['nam']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get presidentId =>
      columnsByName['idChuTich']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get secretaryId =>
      columnsByName['idThuKy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get member1Id =>
      columnsByName['idUyVien1']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get member2Id =>
      columnsByName['idUyVien2']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get member3Id =>
      columnsByName['idUyVien3']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nam',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idChuTich',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idThuKy',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idUyVien1',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idUyVien2',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idUyVien3',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get admissionId =>
      columnsByName['soHoSo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cohort =>
      columnsByName['nienKhoa']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['maHocVien']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['hoTen']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dateOfBirth =>
      columnsByName['ngaySinh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gender =>
      columnsByName['gioiTinh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get placeOfBirth =>
      columnsByName['noiSinh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['dienThoai']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get personalEmail =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schoolEmail =>
      columnsByName['emailHust']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bachelorUniversity =>
      columnsByName['truongTotNghiepDaiHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bachelorMajor =>
      columnsByName['nganhTotNghiepDaiHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bachelorProgram =>
      columnsByName['heTotNghiepDaiHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bachelorGraduationRank =>
      columnsByName['xepLoaiTotNghiepDaiHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bachelorGraduationDate =>
      columnsByName['ngayTotNghiepDaiHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get intendedSpecialization =>
      columnsByName['dinhHuongChuyenSau']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exemptedCourses =>
      columnsByName['hocPhanDuocMien']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get masterMajor =>
      columnsByName['nganhDaoTaoThacSi']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['maTrangThai']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get hasHirstExtension =>
      columnsByName['flag_extend_1']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get hasSecondExtension =>
      columnsByName['flag_extend_2']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get admissionCouncilId =>
      columnsByName['idTieuBanXetTuyen']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get admissionType =>
      columnsByName['idDienTuyenSinh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isAdmissionPaid =>
      columnsByName['thanhToanXetTuyen']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'soHoSo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nienKhoa',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maHocVien',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'noiSinh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dienThoai',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'emailHust',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'truongTotNghiepDaiHoc',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nganhTotNghiepDaiHoc',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'heTotNghiepDaiHoc',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'xepLoaiTotNghiepDaiHoc',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ngayTotNghiepDaiHoc',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dinhHuongChuyenSau',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hocPhanDuocMien',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nganhDaoTaoThacSi',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maTrangThai',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<bool> _column_41(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'flag_extend_1',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const CustomExpression('FALSE'),
    );
i1.GeneratedColumn<bool> _column_42(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'flag_extend_2',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const CustomExpression('FALSE'),
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idTieuBanXetTuyen',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'idDienTuyenSinh',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<bool> _column_45(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'thanhToanXetTuyen',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const CustomExpression('FALSE'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get semester =>
      columnsByName['hocKy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get registrationOpenDate =>
      columnsByName['moDangKy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get registrationCloseDate =>
      columnsByName['dongDangKy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studyStartDate =>
      columnsByName['batDauHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studyEndDate =>
      columnsByName['ketThucHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gradeSubmissionDeadline =>
      columnsByName['hanNhapDiem']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hocKy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'moDangKy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dongDangKy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'batDauHoc',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ketThucHoc',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hanNhapDiem',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['maHocPhan']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vietnameseTitle =>
      columnsByName['tenTiengViet']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get englishTitle =>
      columnsByName['tenTiengAnh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get credits =>
      columnsByName['soTinChi']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseCategory =>
      columnsByName['khoiKienThuc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workload =>
      columnsByName['khoiLuong']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maHocPhan',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tenTiengViet',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tenTiengAnh',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'soTinChi',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'khoiKienThuc',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'khoiLuong',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get supervisorId =>
      columnsByName['idGiangVien']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vietnameseTitle =>
      columnsByName['tenTiengViet']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get englishTitle =>
      columnsByName['tenTiengAnh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['ghiChu']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get studentId =>
      columnsByName['idHocVien']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get assignedDate =>
      columnsByName['ngayGiao']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assignedDecisionNumber =>
      columnsByName['soQdGiao']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defenseDeadline =>
      columnsByName['hanBaoVe']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defenseDecisionNumber =>
      columnsByName['soQdBaoVe']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defenseDate =>
      columnsByName['ngayBaoVe']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get presidentId =>
      columnsByName['idChuTich']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get firstReviewerId =>
      columnsByName['idPhanBien1']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get secondReviewerId =>
      columnsByName['idPhanBien2']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get secretaryId =>
      columnsByName['idThuKy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberId =>
      columnsByName['idUyVien']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get flagTracking =>
      columnsByName['flag_tracking']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get flagPaid =>
      columnsByName['flag_paid']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get flagIgnore =>
      columnsByName['flag_ignore']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get group =>
      columnsByName['group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get year =>
      columnsByName['nam']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isRegisteredForDefense =>
      columnsByName['dangKyBaoVe']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isProfileSubmitted =>
      columnsByName['nopHoSo']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idGiangVien',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ghiChu',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT ()',
      defaultValue: const CustomExpression(''),
    );
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idHocVien',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ngayGiao',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'soQdGiao',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hanBaoVe',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'soQdBaoVe',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ngayBaoVe',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idChuTich',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idPhanBien1',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idPhanBien2',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idThuKy',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idUyVien',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<bool> _column_71(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'flag_tracking',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const CustomExpression('FALSE'),
    );
i1.GeneratedColumn<bool> _column_72(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'flag_paid',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const CustomExpression('FALSE'),
    );
i1.GeneratedColumn<bool> _column_73(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'flag_ignore',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const CustomExpression('FALSE'),
    );
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nam',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dangKyBaoVe',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'nopHoSo',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get cohort =>
      columnsByName['cohort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdTime =>
      columnsByName['created_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedTime =>
      columnsByName['updated_time']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cohort',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<DateTime> _column_79(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'created_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const CustomExpression('CURRENT_TIMESTAMP'),
    );
i1.GeneratedColumn<DateTime> _column_80(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'updated_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const CustomExpression('CURRENT_TIMESTAMP'),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cohort =>
      columnsByName['cohort']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get managementId =>
      columnsByName['management_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get admissionId =>
      columnsByName['admission_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gender =>
      columnsByName['gender']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get dateOfBirth =>
      columnsByName['date_of_birth']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get placeOfBirth =>
      columnsByName['place_of_birth']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['phone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get personalEmail =>
      columnsByName['personal_email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get majorName =>
      columnsByName['major_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get majorId =>
      columnsByName['major_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get majorSpecialization =>
      columnsByName['major_specialization']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get admissionPresidentId =>
      columnsByName['admission_president_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get admissionSecretaryId =>
      columnsByName['admission_secretary_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get admission1stMemberId =>
      columnsByName['admission_1st_member_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get admission2ndMemberId =>
      columnsByName['admission_2nd_member_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get admission3rdMemberId =>
      columnsByName['admission_3rd_member_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get admissionPaid =>
      columnsByName['admission_paid']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get thesis =>
      columnsByName['thesis']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get supervisorId =>
      columnsByName['supervisor_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get secondarySupervisorId =>
      columnsByName['secondary_supervisor_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get schoolEmail =>
      columnsByName['school_email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdTime =>
      columnsByName['created_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedTime =>
      columnsByName['updated_time']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cohort',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'management_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'UNIQUE',
    );
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'admission_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'UNIQUE NOT NULL',
    );
i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gender',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'M\'',
      defaultValue: const CustomExpression('\'M\''),
    );
i1.GeneratedColumn<DateTime> _column_86(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'date_of_birth',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'place_of_birth',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'personal_email',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'major_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'toán học\'',
      defaultValue: const CustomExpression('\'toán học\''),
    );
i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'major_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT 9460101',
      defaultValue: const CustomExpression('9460101'),
    );
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'major_specialization',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'n/a\'',
      defaultValue: const CustomExpression('\'n/a\''),
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'admission_president_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_94(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'admission_secretary_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_95(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'admission_1st_member_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_96(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'admission_2nd_member_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_97(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'admission_3rd_member_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<bool> _column_98(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'admission_paid',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const CustomExpression('FALSE'),
    );
i1.GeneratedColumn<String> _column_99(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thesis',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_100(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'supervisor_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_101(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'secondary_supervisor_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_102(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'school_email',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'UNIQUE',
    );
i1.GeneratedColumn<String> _column_103(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const CustomExpression('CURRENT_TIMESTAMP'),
    );
i1.GeneratedColumn<String> _column_104(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const CustomExpression('CURRENT_TIMESTAMP'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get teacherId =>
      columnsByName['idGiangVien']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['maHocPhan']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_105(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maHocPhan',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get classId =>
      columnsByName['maLopHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['maHocPhan']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get teacherId =>
      columnsByName['idGiangVien']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get registrationCount =>
      columnsByName['soLuongDangKy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get accessUrl =>
      columnsByName['urlTruyCap']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get customBeginDate =>
      columnsByName['customBeginDate']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get customEndDate =>
      columnsByName['customEndDate']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get semester =>
      columnsByName['hocKy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get classroom =>
      columnsByName['phongHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dayOfWeek =>
      columnsByName['ngayHoc']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startPeriod =>
      columnsByName['tietBatDau']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endPeriod =>
      columnsByName['tietKetThuc']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['trangThai']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_106(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'maLopHoc',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_107(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idGiangVien',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_108(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'soLuongDangKy',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_109(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'urlTruyCap',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<DateTime> _column_110(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'customBeginDate',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
      $customConstraints: '',
    );
i1.GeneratedColumn<DateTime> _column_111(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'customEndDate',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_112(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hocKy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_113(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phongHoc',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_114(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ngayHoc',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_115(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tietBatDau',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_116(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tietKetThuc',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_117(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'trangThai',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get classId =>
      columnsByName['classId']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teacherId =>
      columnsByName['teacherId']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get contribution =>
      columnsByName['contribution']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_118(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'classId',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_119(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'teacherId',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_120(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const CustomExpression('1'),
    );
i1.GeneratedColumn<double> _column_121(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'contribution',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 1.0',
      defaultValue: const CustomExpression('1.0'),
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get courseClassId =>
      columnsByName['idLopTinChi']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get studentId =>
      columnsByName['idHocVien']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_122(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idLopTinChi',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_123(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'idHocVien',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedVirtualTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get idGiangVien =>
      columnsByName['idGiangVien']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get idHocVien =>
      columnsByName['idHocVien']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tenTiengAnh =>
      columnsByName['tenTiengAnh']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tenTiengViet =>
      columnsByName['tenTiengViet']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get giangVien =>
      columnsByName['giangVien']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hocVien =>
      columnsByName['hocVien']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_124(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_125(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'idGiangVien',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_126(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'idHocVien',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_127(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tenTiengAnh',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_128(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tenTiengViet',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_129(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'giangVien',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_130(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hocVien',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
